$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        400:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})
$('.owl-carousel-two').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        400:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})